connect-foundation/2019-05

.gitignore
- #2 [FE/BE] gitignore만들기
- .idea폴더가 제대로 ignore되지 않는 문제 수정
- public 폴더가 올라가지 않는 문제 수정
=> [191111] gitignore 파일 수정

client/package.json, client/public/index.html
- #3 [FE] React 개발환경 세팅
- public 폴더 추가
- package.json 에서 패키지 이름, 설명, 저자 등 변경
=> 191111 public 폴더 추가 및 package.json 수정

README.md
- README.md file 수정
- `npx readme-md-generator`를 이용하여 template 생성
- 우리 프로젝트의 환경에 맞도록 각색(추가 업데이트 무조건 필요)
- 추가로 들어가야 하는 사항, 오탈자 확인 부탁드립니다. 
- https://github.com/kefranabg/readme-md-generator
=> [191118] README.md file 1차 수정

client/src/components/common/Header/Header.scss
position: sticky
top: 0
background-color: white
를 사용하여 고정했으나 검토가 필요합니다.
=> [191121] Header 컴포넌트 고정 완료

server/app.js, server/middlewares/createError.js, server/middlewares/passport.js, server/package.json, server/routes/auth.js, server/routes/error.js, server/yarn.lock
- #36 [BE] Oauth2.0 네이버 로그인 환경 구축
+ 전체적인 코드 통일성
- 네이버에 QuickKick 서비스를 등록 후 client 권한을 발급
- passport-naver를 통해 네이버 로그인과 QuickKick 서비스를 연결
- 아직 토큰 발급을 통한 확인이 이루어지진 않았음
- 우리측 DB가 완성되면 user 정보 조회 후 회원가입과 로그인 분기를 시킬 예정
=> [191121] Oauth2.0 네이버 로그인 환경 구축 (미완)

README.md
- none
- 서비스 안내,
- 기술 스택
- 프로젝트 구조
- 팀원별 담당 분야
- 뱃지 등 업데이트
=> [191122] README.md file 업데이트

client/src/App/index.jsx, client/src/components/common/Header/Header.scss, client/src/components/common/Header/index.jsx, client/src/index.css, client/src/view/index.js, client/src/view/myteam.jsx
- 1200px 컨테이너 클래스 추가(.grid-container)
- 컨테이너 추가에 따른 헤더 스타일링 조정
- myteam router 추가
=> [20191125] 헤더 스타일 수정, myteam router 추가

client/.prettierrc, client/src/components/common/Footer/Footer.scss, client/src/components/common/Footer/index.jsx, server/.prettierrc
- none
- 복잡한 Footer보다는 simple한 것이 더 낫다는 판단에 대폭 간단하게 만들었다.
=> [191125] Footer component 간단한 수정

client/src/App/index.jsx, client/src/components/common/Header/index.jsx, client/src/components/home/HomeIntroduce/index.jsx, client/src/components/home/HomeIntroduce/index.scss, client/src/components/home/HomeMatchStatus/index.jsx, client/src/components/home/HomeMatchStatus/index.scss, client/src/components/home/HomeQuickMatch/index.jsx, client/src/components/home/HomeQuickMatch/index.scss, client/src/components/home/HomeTeamRanking/index.jsx, client/src/components/home/HomeTeamRanking/index.scss, client/src/components/home/index.js, client/src/view/home.jsx, client/src/view/index.js, client/src/view/myteam.jsx, client/src/view/ranking.jsx
- Home 화면에 필요한 컴포넌트들 생성
- 기본적인 레이아웃 배치 완료
- Router 연결까지 완료
=> [191126] Home 화면 레이아웃 완성

client/package.json, client/src/components/common/Header/Header.scss, client/src/components/common/Header/index.jsx, client/src/index.css, client/yarn.lock
- header 수정(링크, 폰트, 아이콘)
- fontawesome 아이콘 추가
=> [20191126] Header 스타일링, index.css에 reset 추가

client/src/App/App.test.jsx
- none
- /매치매치/ 정규표현식을 만족하면 패스하는 기존의 방식 대신
heading role을 가지고 텍스트 컨텐트를 매치시키는 방식 채택
=> [191126] 테스트 코드 수정

client/.eslintrc, client/package.json, client/src/App/App.test.jsx, client/src/components/common/Button/Button.scss, client/src/components/common/Button/index.jsx, client/src/components/common/Header/index.jsx, client/src/components/match/MatchList/MatchList.test.jsx, client/src/components/match/MatchList/index.jsx, client/src/components/match/MatchList/index.scss, client/src/components/match/MatchMap/index.jsx, client/yarn.lock
- none
- test 코드 수정
- eslint, prettier 충돌 관련 이슈 해결
=> [191127] 테스트 코드 수정, eslint과 prettier 충돌 관련 이슈 해결

client/src/App/index.jsx, client/src/components/common/Header/Header.scss, client/src/components/common/Header/index.jsx, client/src/index.css, client/src/views/error/index.jsx, client/src/views/index.js, server/generated/prisma-client/index.d.ts, server/generated/prisma-client/prisma-schema.js, server/resolver.js, server/routes/auth.js, server/schema.graphql
=> [191127] FE error페이지 추가, header 수정,  graphQL 스키마 변경

client/package.json, client/src/Root.jsx, client/src/components/common/MatchFilter/index.jsx, client/src/components/common/MatchFilter/index.scss, client/src/contexts/FilterContext.jsx, client/src/setContexts/setFilterContext.jsx, client/yarn.lock
- useContext의 적용
- Context의 state와 state조작 부분을 나눴음
- 아직은 FilterContext만 있으나 추후 필요한 state에 따라 추가 예정
=> [191128] useContext를 통한 전역 state 관리

client/src/components/common/Button/Button.scss, client/src/components/common/Header/index.jsx, client/src/components/home/HomeIntroduce/index.jsx, client/src/components/home/HomeIntroduce/index.scss, client/src/components/home/HomeMatchStatus/index.jsx, client/src/components/home/HomeMatchStatus/index.scss, client/src/components/home/HomeQuickMatch/index.jsx, client/src/components/home/HomeQuickMatch/index.scss, client/src/components/home/HomeTeamRanking/index.jsx, client/src/components/home/HomeTeamRanking/index.scss, client/src/components/match/MatchList/index.jsx, client/src/components/match/MatchList/index.scss, client/yarn.lock
- none
- 매치 일자, 시작 시각, 장소 등을 카드 형태로 구현함
=> [191128] MatchCard component 1차 구현

client/src/App/App.test.jsx, client/src/components/common/Header/Header.test.jsx
- none
- nav bar의 제목이 바뀜에 따라 '없는 element'를 찾아 test하는 코드 제거
=> [191128] test code 수정

.travis.yml, server/.env.enc
=> [191128] travis ci 관련 코드 적용

.travis.yml, server/.env.enc
=> TEST: travis 환경 파일 변경

.travis.yml, server/Dockerfile, server/middlewares/passport.js, server/package.json, server/routes/auth.js
=> [191128] travis build 추가

.gitignore, client/Dockerfile, client/conf/conf.d/default.conf, client/conf/conf.d/vhosts.conf
- gitignore에 personal폴더 추가. 개인 테스트 및 작업 용이점
- frontend build시 필요한 dockerfile 및 nginx 설정파일 추가(임시)
=> [191202] gitignore 파일 수정 및 build용 파일 추가

client/src/components/match/MatchCard/index.jsx, client/src/components/match/MatchMap/index.jsx, client/src/components/match/MatchMap/index.scss
- none
- FIX: spinner가 지도 중점에 위치하도록 변경
- REFACTOR: promise를 async/await 구문으로 변경, minor한 수정
=> [191204] spinner 위치 수정, 간단한 구문 수정

client/src/commonStyle.scss, client/src/components/common/DateTimeFilter/index.jsx, client/src/components/common/Header/Header.scss, client/src/components/home/HomeQuickMatch/index.jsx, client/src/components/home/HomeQuickMatch/index.scss, client/src/components/match/MatchList/index.jsx, client/src/components/match/MatchList/index.scss, server/resolver.js, server/schema.graphql
- home 화면 간단 스타일 조절
- matchList를 filterContext 수정에 맞춰 바뀌어지도록 변경
- matchList에서 보내는 쿼리에 맞춰 graphQL 쿼리 스키마 수정
=> [191206] filter에 맞추어 list 불러오도록 변경과 그에따른 style 변경

client/src/components/match/MatchRegistModal/index.jsx, server/middlewares/passport.js, server/routes/auth.js, server/routes/user.js
- 아직 기본 정보 입력없이 naver id만 저장
- 추후 서비스를 이용시 기본 정보 최초 1회 입력받을 예정
=> [121210] 최초 로그인 시 회원DB에 자동 저장 (회원가입)

client/src/components/match/MatchMap/index.jsx
=> FIX: 스피너 위치 수정

client/src/Root.jsx, client/src/components/common/SideBar/index.jsx, client/src/contexts/User/Context.jsx, client/src/contexts/User/Reducer.js, server/app.js, server/package.json, server/routes/user/controller.js, server/yarn.lock
- 로그인 정보를 저장할 context 생성
- axios에서 cors에러가 발생하여 고생 중
=> [191211] front에서 네이버 로그인 연동 (cors 에러 미해결)

client/src/components/common/SideBar/index.jsx, server/app.js
JWT를 발급받고 확인하는 API를 요청하는데 있어서 CORS 이슈 발생
api server단에서 cor 모듈에 옵션을 주어 해결
=> FIX: CORS 이슈 해결

client/src/components/common/SideBar/index.jsx, client/src/components/common/SideBar/index.scss, server/__tests__/enpoint.test.js, server/app.js, server/package.json, server/routes/mail.js, server/yarn.lock
- none
- TEST: server단 테스트 코드 작성
- FIX: SideBar가 viewport 바깥으로 밀려나는 상황 fix
- CHORE: /mail router 반환 json 수정 등
=> [191211] sidebar position 수정, server단 test code 작성

client/src/components/common/Header/index.jsx, client/src/components/common/SideBar/index.jsx
=> FIX: 미처 stage하지 못하여 commit하지 못한 파일들 commit

client/src/components/common/DateTimeFilter/index.jsx, client/src/components/common/Header/index.jsx, client/src/components/common/SideBar/index.jsx, client/src/components/match/MatchMap/index.jsx, client/src/components/match/MatchRegist/index.jsx, client/src/components/match/MatchRegistModal/index.jsx, client/src/contexts/Filter/ActionCreator.js, client/src/contexts/Filter/index.js, client/src/contexts/Match/ActionCreator.js, client/src/contexts/Match/index.js, client/src/contexts/SideBar/ActionCreator.js, client/src/contexts/SideBar/index.js, client/src/contexts/User/ActionCreator.js, client/src/contexts/User/index.js, client/src/views/match/index.jsx, server/yarn.lock
=> [191212] actionCreator 적용

client/src/commonStyle.scss, client/src/components/common/SideBar/index.jsx, client/src/components/common/SideBar/index.scss, client/src/components/home/HomeQuickMatch/index.jsx, client/src/components/home/HomeQuickMatch/index.scss
- none
1. footer 아래에 공간 없앰
2. side bar 왼편에 shadow 잘못 넣은 것 수정
3. 배경색깔을 공통 변수로 둠. image 크기 및 위치 수정
4. 메인 화면을 좌우로 나누어 각각 필터, 이미지 배치
=> [191213] style 관련 자잘한 부분 수정

client/src/components/home/HomeQuickMatch/index.jsx, client/src/components/home/HomeQuickMatch/index.scss, client/src/views/home/index.jsx, client/src/views/match/index.jsx, client/src/views/myteam/index.jsx
=> [191213] 메인페이지 스타일 변경

.travis.yml
=> FIX: CI/CD 수정

.travis.yml
=> CHORE: travis 설정파일 수정

.travis.yml, server/app.js, server/views/error.jade, server/views/index.jade, server/views/layout.jade
=> [191213] 사용하지 않는 파일 삭제 및 코드 제거

client/src/components/match/MatchList/index.jsx, client/src/components/myteam/TeamIntroduction/index.jsx, client/src/components/myteam/TeamIntroduction/index.scss
- teamintroduction에 teamuniqueId값 추가. 추후에 다른 사람에게 값을 공유하여 직접 가입할 수 있게 하기 위함.
- match Context에 적용되어있는 선택된 '구'의 값을 graphQL에 적용하여 필터링
=> [191213] TeamIntroduction 일부 요소 추가, MatchList에 match context 값 적용.

client/src/components/match/MatchMap/index.jsx, server/middlewares/findOrCreateUser.js, server/middlewares/passport.js, server/package.json, server/routes/auth/controller.js, server/routes/auth/index.js, server/utils/convertToString.js, server/yarn.lock
- Oauth2.0 카카오 로그인 추가
- jwt 발급 및 로그인 확인 완료
- 기존에 있던 네이버 로그인과의 병행 운용이 가능하도록 조정
=> [191215] Oauth2.0 kakao-login 추가

client/package.json, client/src/components/myteam/TeamIntroduction/index.jsx, client/yarn.lock
- sanitize-html 모듈 사용하여 스크립트 필터링하도록 변경.
=> [191215] MyTeam 폼 입력값 xss 필터 적용

client/src/App/index.jsx, client/src/components/myteam/TeamIntroduction/index.scss, client/src/components/myteam/TeamMembers/index.jsx, client/src/components/myteam/TeamMembers/index.scss, client/src/components/myteam/index.js, client/src/views/match/index.jsx, client/src/views/myteam/index.jsx, server/generated/prisma-client/index.d.ts, server/generated/prisma-client/index.js, server/generated/prisma-client/prisma-schema.js, server/prisma/datamodel.prisma, server/schema.graphql
- 회원가입자의 가입 수단을 기록할 수 있는 authProvider 필드 추가.
- 팀 정보 페이지의 팀 멤버 정보 출력하는 컴포넌트 기본 파일 작성
=> [191216] 데이터모델 수정 및 teamMember 기본 파일 생성

server/middlewares/findOrCreateUser.js, server/routes/auth/controller.js, server/routes/user/controller.js
- jwt에 authProvider 추가
- jwt 해석하는 api 수정
=> [191216] 로그인 과정 중 authProvider 정보 추가하여 진행

client/src/contexts/User/ActionCreator.js, client/src/contexts/User/InitialState.js, client/src/contexts/User/Reducer.js
=> [191217] User CONTEXT에 user team 정보를 같이 가지고 있도록 수정.

server/resolver.js
=> [191217] resolver에서 Player 관계성 설정이 잘못되어 있던 부분 수정.

client/src/components/match/MatchRegist/index.jsx, client/src/components/match/MatchRegistModal/index.jsx, server/package.json, server/resolver.js, server/schema.graphql
- 신규 매치가 등록이 된다.
- 매치 등록 후 모달창 꺼짐.
- 입력값 검증 및 xss 필터.
=> [191217] 신규 매치 등록 기능 완성

client/src/components/common/SideBar/index.jsx, client/src/components/common/SideBar/index.scss, client/src/util/functions.js
- none
- push notification을 구현하기 위해서는 user browser에서
permission을 설정해 주어야 하는데, 한 번 허용을 하지 않게 하면
user가 다시 알림 신청을 하기 위해서는 번거로움을 감소해야
하기 때문에 버튼을 만들어 주었다.
=> [191217] SideBar에 push 알림 on/off버튼 만듦

client/src/components/myteam/TeamIntroduction/index.jsx, client/src/views/myteam/index.jsx
- userContext에 등록한 playerTeam 값을 사용하여 쿼리를 보냄.
- 해당 값이 없을 경우는 main page로 redirect하도록 개발.
=> [191217] 실제 로그인한 user의 소속 팀에 맞춰 정보 가져오도록 변경.

client/src/components/match/MatchApplyModal/index.jsx, client/src/components/match/MatchList/index.jsx
- match를 올린 사람에게 알림을 보내기 위한 author 데이터 추가.(mail, sms, push)
=> [191217] 매치 신청 시 server로 보낼 match data 확장

client/src/App/index.jsx, client/src/components/common/SideBar/index.jsx, client/src/components/mypage/UserInfoForm/index.jsx, client/src/components/mypage/index.js, client/src/views/home/index.jsx, client/src/views/index.js, client/src/views/mypage/index.jsx, client/src/views/myteam/index.jsx
- 서비스를 이용하기에 필요한 최소 user 정보의 입력을 받는 곳
- 라우터 및 진입만 완성
- 입력 form 추후 개발 예정
=> [191218] 최초 1회 user 정보 입력을 위한 /mypage view 추가 (미완)

client/src/components/match/MatchCard/index.jsx, client/src/components/myteam/TeamIntroduction/index.jsx, client/src/components/myteam/TeamMembers/index.jsx, client/src/contexts/User/Reducer.js
- 선언 후 미사용 변수들 삭제 진행 (추가진행 요망)
=> [191218] 선언 후 미사용 변수들 삭제 작업 (1차)

server/routes/notification/controller.js
=> FIX: 잘못된 코드 수정

client/public/serviceWorker.js, client/src/components/match/MatchApplyModal/index.jsx, client/src/components/match/MatchRegist/index.jsx, client/src/components/match/MatchRegistModal/index.jsx, client/src/components/myteam/TeamIntroduction/index.jsx, client/src/container/auth/index.jsx, client/src/util/requestOptionCreator.js, client/src/views/myteam/index.jsx
- userContext에서 관리하는 상태 변경
- 리팩토링
=> [191219] 상태 관리 및 리팩토링

client/src/components/common/SideBar/index.jsx
- 
- Emblem component에 playerInfo를 넣어 주지 않아 생기는 에러 해결
=> [191219] 긴급 수정

client/src/components/common/SideBar/index.jsx
- sidebar에 유저 정보 입력 이식 완료
- 디자인 작업 필요
=> [191219] sidebar에 유저 정보 입력 이식 완료

client/src/components/common/SideBar/index.jsx, client/src/components/sidebar/TeamCodeForm/index.jsx, client/src/components/sidebar/UserInfoForm/index.jsx
- <TeamCodeForm /> 입력 완료시 즉시 sidebar에 팀정보 보여주기
- <UserInfoForm /> 입력 완료시 즉시 sidebar에 팀정보 보여주기
=> [191219] user의 정보, 팀등록 여부에 따른 개인화 된 sidebar 완성

client/src/components/common/DateTimeFilter/index.jsx, client/src/components/common/DateTimeFilter/index.scss
- 지역 정보 미선택 시 시간대에 맞는 모든 알림을 받는것은 낭비가 심하다는 결정.
데이트 필터 일부 스타일 수정 포함.
=> [191220] 알림 신청 시, 지역 정보를 선택해야만 신청이 가능하도록 수정.

server/resolver.js
- where절을 작성하는 방식이 맞지 않아 데이터가 잘못 불려오고 있었음.
=> [191220] Notifier 타입 리졸버가 잘못 작성되어있던 부분 수정.

client/src/components/match/MatchApplyModal/index.jsx, client/src/container/auth/index.jsx, server/routes/notification/controller.js, server/routes/notification/index.js
=> [191220] 버그 수정

client/src/commonStyle.scss, client/src/components/common/DateTimeFilter/index.jsx, client/src/components/common/DateTimeFilter/index.scss, client/src/components/match/MatchList/index.jsx, client/src/components/match/MatchMap/index.jsx, client/src/components/match/MatchMap/index.scss, client/src/components/match/MatchRegist/index.scss, client/src/views/match/index.jsx, client/src/views/match/index.scss
=> [191221] 메인 색상 변경, 필터를 맵 위쪽으로 이동

client/src/components/common/SideBar/index.jsx, client/src/components/myteam/TeamIntroduction/index.jsx, client/src/container/auth/index.jsx, client/src/util/query.js
- 팀 생성 후 팀 화면 진입했을 때, 팀 정보가 없어서 함수 오류뜨던 부분도 수정
=> [191221] query backtick 이 없어 오류가 나던 부분 수정.

client/src/commonStyle.scss, client/src/components/common/SideBar/index.jsx, client/src/components/common/SideBar/index.scss, client/src/components/match/MatchCard/index.scss, client/src/components/match/MatchRegist/index.scss, client/src/components/myteam/TeamMatchList/index.scss, client/src/components/myteam/TeamMembers/index.jsx, client/src/components/myteam/TeamMembers/index.scss, client/src/index.scss, server/routes/notification/controller.js
- none
- 알림창 스크롤바 제거 …
- h2 크기수정, 버튼 hover했을 시 opacity 주는 코드 작성
=> [191221] 전반적인 스타일 작업

client/src/commonStyle.scss, client/src/components/common/DateTimeFilter/index.scss, client/src/components/myteam/TeamMembers/index.jsx, client/src/components/myteam/TeamMembers/index.scss
- 
- class, id를 부여해서 스타일을 입히지 않고 바로 수정을 하여
- 예상치 못한 결과를 야기시켰기에 해당 부분을 수정해 주었다.
- 또한 dateFilter를 우리 web app의 메인 컬러에 맞게 바꾸었다.
=> [191222] 망가진 달력 스타일 보수

client/src/components/common/DateTimeFilter/index.scss, client/src/components/common/SideBar/index.jsx, client/src/components/common/SideBar/index.scss, client/src/components/match/MatchCard/index.scss, client/src/components/match/MatchRegist/index.scss, client/src/components/myteam/TeamMatchList/index.scss
- none
- opacity를 주지 않은 부분, 너무 많이 준 부분을 조절
- 사이드바 내부 버튼 레이아웃 수정
- 알림 내역 버튼 call to action 추가
- 매치 페이지 매치 필터 글씨 가운데 정렬
=> [191222] 자잘한 스타일 수정

client/src/components/myteam/TeamIntroduction/index.scss, client/src/components/myteam/TeamMatchList/index.jsx, client/src/components/myteam/TeamMatchList/index.scss, client/src/components/myteam/TeamMembers/index.jsx, client/src/components/myteam/TeamMembers/index.scss, client/src/views/myteam/index.jsx
- 전체적인 통일성을 위해 멤버 리스트와 동일한 스타일의 표로 변경.
- 클릭 시 슬라이드 다운 효과 생성.
=> [191222] 매치 신청자 리스트 출력 스타일 조정

client/src/components/common/DateTimeFilter/index.jsx
- undefined 의 seq가 없다는 오류 메시지 출력.
=> [191222] 알림신청클릭 시 로그인이 안되어 있으면 오류가 뜨는 부분 수정.

client/src/components/common/SideBar/index.jsx, client/src/components/common/SideBar/index.scss, client/src/components/sidebar/TeamCodeForm/index.jsx, client/src/components/sidebar/TeamCreationForm/index.jsx, client/src/components/sidebar/UserInfoForm/index.jsx
=> [191222] sidebar 버튼 ui 개선

server/dummy-data.js, server/seed.js
- none
- DB: dummy data 삽입 코드 완성
=> [191222] dummy data 삽입 코드 완성

server/dummy-data.js, server/seed.js
=> [191222] 더미 데이터 삽입 로직 오류, 오타 등 수정.

server/middlewares/matchNotification.js, server/utils/district.js
- none
- matchInfo(startTime, 장소)를 넘겨주어 동적으로
메세지를 작성할 수 있게 하였다.
=> [191222] SMS 본문이 하드코딩되어 있던 부분 수정

server/resolver.js, server/schema.graphql
- pagination을 위해 connection 쿼리 적용.
=> [191222] graphQL 스키마 수정

client/public/serviceWorker.js, client/src/components/common/SideBar/index.jsx, client/src/components/match/MatchCard/index.jsx, client/src/components/match/MatchList/index.jsx, client/src/components/match/MatchList/index.scss, client/src/components/match/MatchRegistModal/index.jsx, client/src/util/query.js, client/src/views/myteam/index.jsx
=> [191222] 배포 전 필요한 수정사항 정리

server/middlewares/matchNotification.js, server/utils/nodemailer.js
- none
- replace(/-/g, '')을 이용하여 작업을 수행하였다.
=> [191222] 유저가 폰번호를 하이픈을 넣어 입력했을 때 그것을 없애주게 함.

client/public/serviceWorker.js, server/middlewares/matchNotification.js, server/routes/notification/controller.js, server/utils/subscriptionMap.js
server notification web-push 추가 및 버그 수정
=> [191223] server notification web-push 추가 및 버그 수정

server/utils/nodemailer.js
- none
- rejectUnauthorized인데 d가 빠져 있었음.
=> [191223] node-mailer에 잘못된 옵션 수정

client/src/components/match/MatchList/index.jsx
- <예시입니다. 이 부분을 지우고 PR을 작성하세요>
- #2 - [FE/BE] .gitignore 만들기
- <예시입니다. 이 부분을 지우고 PR을 작성하세요>
- 팀원별 필요한 무시할 파일들을 기존 .gitignore 파일에 추가
-
=> HOTFIX: 필터 적용이 잘 안되던 부분 해결.
